// Git-Templates/ProjectLanguageFiles/Education/!Learn/Learn-VueJS/Vue/PROJECT_LANG_1.vue
<div id="plang1">
  <p>{{ message }}</p>
</div>
<script>
new Vue({
  el: '#plang1',
  data: {
    message: 'Project language file 1\nFor: seanpm2001/Learn-VueJS\nAbout:\nI decided to make Vue.js the main project language file for this project (Seanpm2001/Learn-VueJS) as Vue.js is the language this project is dedicated to, because this project is about learning the Vue.js programming language. It only makes sense to Vue.js the official language for this project. It is getting its own project language file, starting here.\n'
  }
})
</script>
// Output:
// Project language file 1
// For: seanpm2001/Learn-VueJS
// About:
// I decided to make Vue.js the main project language file for this project (Seanpm2001/Learn-VueJS) as Vue.js is the language this project is dedicated to, because this project is about learning the Vue.js programming language. It only makes sense to Vue.js the official language for this project. It is getting its own project language file, starting here.

/* File info
* File type: Vue.js source file (*.vue *.js)
* File version: 1 (2022, Friday, September 2nd at 4:56 pm PST)
* Line count (including blank lines and compiler line): 25
*/

// End of script

// Git-Templates/ProjectLanguageFiles/SNU/2D/ProgrammingTools/Svelte/Svelte/PROJECT_LANG_1.svelte
<script>
	// Project language file 1
	// For: SNU/2D/ProgrammingTools/IDE/Svelte
	// About:
  // I decided to make Svelte the main project language file for this project (SNU / 2D / Programming Tools / IDE / Svelte) as this is a Svelte IDE, and it needs its main language to be represented here.
	let description = 'I decided to make Svelte the main project language file for this project (SNU / 2D / Programming Tools / IDE / Svelte) as this is a Svelte IDE, and it needs its main language to be represented here.';
</script>
// Start of script
<h1>Project language file 1</h1>
<h2>For: SNU/2D/ProgrammingTools/IDE/Svelte</h2>
<h3>About:</h3>
<h4>{description}!</h4>
// File info
// File type: Svelte source file (*.svelte)
// File version: 1 (2022, Monday, February 28th at 2:40 pm)
// Line count (Including blank lines and compiler line): 18
// End of script
